In [3]:
import uproot
import pandas as pd
import numpy as np

In [15]:
# gen level
tree_tt_gen = uproot.open("../MVAFILE_GEN_AllHiggs_tt.root")["ntuple"]
print('loaded root file')
variables_gen = [
            "wt_cp_sm", "wt_cp_ps", "wt_cp_mm", "rand",
            "dm_1", "dm_2",
            "pi_E_1", "pi_px_1", "pi_py_1", "pi_pz_1", # charged pion 1
            "pi_E_2", "pi_px_2", "pi_py_2", "pi_pz_2", # charged pion 2
            "pi0_E_1", "pi0_px_1", "pi0_py_1", "pi0_pz_1", # neutral pion 1
            "pi0_E_2", "pi0_px_2", "pi0_py_2", "pi0_pz_2", # neutral pion 2,
            'metx', 'mety',
            'sv_x_1', 'sv_y_1', 'sv_z_1', 'sv_x_2', 'sv_y_2', 'sv_z_2',
            ]
df_tt_gen = tree_tt_gen.pandas.df(variables_gen)

loaded root file

,wt_cp_sm,wt_cp_ps,wt_cp_mm,rand,dm_1,dm_2,pi_E_1,pi_px_1,pi_py_1,pi_pz_1,...,pi0_py_2,pi0_pz_2,metx,mety,sv_x_1,sv_y_1,sv_z_1,sv_x_2,sv_y_2,sv_z_2
entry,,,,,,,,,,,,,,,,,,,,,
0,1.601494,0.310697,0.581832,0.529761,1.0,1.0,10.994950,8.404180,6.915075,1.555936,...,-3.580417,0.147664,21.212856,16.206368,0.023583,0.019393,0.005763,-0.581665,-0.513909,0.018126
1,1.616939,0.048255,0.718878,0.625262,10.0,0.0,80.198681,-3.553889,36.892234,-71.120615,...,0.000000,0.000000,4.612193,-13.801276,-0.097911,0.989190,-1.882611,0.000394,-0.001668,-0.005869
2,0.145634,1.555381,0.524301,0.600541,1.0,10.0,63.063316,33.907569,22.022118,48.396957,...,0.000000,0.000000,21.313398,48.146972,0.047770,0.031705,0.067133,-0.085217,0.345833,0.142905
3,1.487983,0.444336,1.316065,0.764755,1.0,1.0,29.041587,24.443190,-4.880136,-14.903323,...,-16.557451,-94.600909,6.099251,-8.346872,0.264949,-0.061602,-0.161944,-0.120283,-0.045656,-0.260196
4,0.370084,1.765682,1.648769,0.604970,10.0,10.0,5.500041,-4.350674,-2.053902,2.661596,...,0.000000,0.000000,-0.671295,1.881746,-0.304889,-0.132517,0.176034,0.196662,0.151155,0.536159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19126441,0.908689,0.341760,1.138433,0.430148,1.0,1.0,85.222318,42.140033,74.047921,-1.986735,...,-26.928099,0.490041,8.576651,5.678794,0.005442,0.009449,-0.000291,0.112904,-0.323324,0.006656
19126442,0.309599,0.199739,0.031921,0.455971,1.0,1.0,4.310472,3.256766,-0.998351,2.637699,...,10.171089,-65.467882,20.108821,-4.571250,0.025354,-0.009183,0.022112,0.017088,0.004278,-0.028219
19126443,1.957682,0.002597,0.964876,0.200885,10.0,10.0,23.070319,-11.515198,8.426885,-18.127547,...,0.000000,0.000000,-41.590696,-6.043155,-0.083009,0.058232,-0.123699,-0.016278,-0.044642,-0.025349
19126444,0.759525,1.291579,1.800639,0.612383,1.0,1.0,10.495568,-0.591211,5.297255,9.040300,...,-17.039955,97.285611,-27.292657,12.838059,-0.030071,0.223568,0.407931,-0.386126,-0.197205,1.091975
19126445,0.331289,1.978143,1.343206,0.750266,1.0,1.0,71.350386,14.121561,-60.373793,-35.305022,...,-5.805427,-16.456594,20.411618,-49.315305,0.046878,-0.206266,-0.120727,0.120289,-0.073203,-0.212698

In [10]:
tree_tt_gen.keys()

[b'rand',
 b'wt_cp_sm',
 b'wt_cp_ps',
 b'wt_cp_mm',
 b'pi_px_1',
 b'pi_py_1',
 b'pi_pz_1',
 b'pi_E_1',
 b'pi2_px_1',
 b'pi2_py_1',
 b'pi2_pz_1',
 b'pi2_E_1',
 b'pi3_px_1',
 b'pi3_py_1',
 b'pi3_pz_1',
 b'pi3_E_1',
 b'pi_px_2',
 b'pi_py_2',
 b'pi_pz_2',
 b'pi_E_2',
 b'pi2_px_2',
 b'pi2_py_2',
 b'pi2_pz_2',
 b'pi2_E_2',
 b'pi3_px_2',
 b'pi3_py_2',
 b'pi3_pz_2',
 b'pi3_E_2',
 b'pi0_px_1',
 b'pi0_py_1',
 b'pi0_pz_1',
 b'pi0_E_1',
 b'pi0_px_2',
 b'pi0_py_2',
 b'pi0_pz_2',
 b'pi0_E_2',
 b'sv_x_1',
 b'sv_y_1',
 b'sv_z_1',
 b'sv_x_2',
 b'sv_y_2',
 b'sv_z_2',
 b'dm_1',
 b'dm_2',
 b'metx',
 b'mety']

In [4]:
df_tt_gen.head()

,wt_cp_sm,wt_cp_ps,wt_cp_mm,rand,dm_1,dm_2,pi_E_1,pi_px_1,pi_py_1,pi_pz_1,...,pi0_E_1,pi0_px_1,pi0_py_1,pi0_pz_1,pi0_E_2,pi0_px_2,pi0_py_2,pi0_pz_2,metx,mety
entry,,,,,,,,,,,,,,,,,,,,,
0,1.601494,0.310697,0.581832,0.529761,1.0,1.0,10.994950,8.404180,6.915075,1.555936,...,22.769319,16.963737,14.569723,4.287013,5.309484,-3.915509,-3.580417,0.147664,21.212856,16.206368
1,1.616939,0.048255,0.718878,0.625262,10.0,0.0,80.198681,-3.553889,36.892234,-71.120615,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.612193,-13.801276
2,0.145634,1.555381,0.524301,0.600541,1.0,10.0,63.063316,33.907569,22.022118,48.396957,...,9.501558,5.273859,3.399763,7.133682,0.000000,0.000000,0.000000,0.000000,21.313398,48.146972
3,1.487983,0.444336,1.316065,0.764755,1.0,1.0,29.041587,24.443190,-4.880136,-14.903323,...,8.565440,7.234810,-1.743771,-4.238552,105.655770,-44.041370,-16.557451,-94.600909,6.099251,-8.346872
4,0.370084,1.765682,1.648769,0.604970,10.0,10.0,5.500041,-4.350674,-2.053902,2.661596,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.671295,1.881746

In [16]:
df_tt_gen.to_pickle('./df_tt_gen.pkl')

In [6]:
df_tt_gen = pd.read_pickle('./df_tt_gen.pkl')

In [7]:
channel = 'rho_rho'

In [10]:
# gen level data NEED TO CHECK FOR TAU DECAY MODE LABEL
if channel == 'rho_rho':
    df_rho = df_tt_gen[(df_tt_gen['dm_1']==1) & (df_tt_gen['dm_2']==1)]
    df = df_rho.drop(["dm_1","dm_2","wt_cp_sm", "wt_cp_ps", "wt_cp_mm", "rand"], axis=1).reset_index(drop=True)
elif channel == 'rho_a1':
    df_rho_a1 = df_tt_gen[(df_tt_gen['dm_1']==1) & (df_tt_gen['dm_2']==10)]
    df = df_rho_a1.drop(["dm_1","dm_2","wt_cp_sm", "wt_cp_ps", "wt_cp_mm", "rand"], axis=1).reset_index(drop=True)
elif channel == 'a1_a1':
    df_a1_a1 = df_tt_gen[(df_tt_gen['dm_1']==10) & (df_tt_gen['dm_2']==10)]
    df = df_a1_a1.drop(["dm_1","dm_2","wt_cp_sm", "wt_cp_ps", "wt_cp_mm", "rand"], axis=1).reset_index(drop=True)
else:
    print('CHANNEL not understood!')
df['met'] = np.sqrt(df['metx']**2+df['mety']**2)

In [11]:
df.head()

,pi_E_1,pi_px_1,pi_py_1,pi_pz_1,pi_E_2,pi_px_2,pi_py_2,pi_pz_2,pi0_E_1,pi0_px_1,pi0_py_1,pi0_pz_1,pi0_E_2,pi0_px_2,pi0_py_2,pi0_pz_2,metx,mety,met
0,10.994950,8.404180,6.915075,1.555936,47.278106,-35.655722,-31.039530,0.645695,22.769319,16.963737,14.569723,4.287013,5.309484,-3.915509,-3.580417,0.147664,21.212856,16.206368,26.695162
1,29.041587,24.443190,-4.880136,-14.903323,21.899677,-9.257474,-3.170107,-19.591477,8.565440,7.234810,-1.743771,-4.238552,105.655770,-44.041370,-16.557451,-94.600909,6.099251,-8.346872,10.337850
2,10.037782,6.726276,6.604666,3.445747,57.100717,-54.699795,11.793125,11.372204,49.058912,32.886199,32.946126,15.485779,10.529916,-10.096570,1.927421,2.281501,-1.949966,7.964842,8.200066
3,61.296869,-2.413211,30.969841,52.842521,33.248954,3.150124,-8.464115,31.998577,4.134056,-0.268372,2.131055,3.529700,111.978542,12.034646,-28.727843,107.559537,8.038632,-2.798081,8.511690
4,46.820840,21.968763,27.752590,-30.648634,14.125586,10.222310,8.853672,4.077938,9.237175,4.012812,5.591140,-6.159843,66.680248,48.734111,40.731621,20.301691,57.291477,68.616048,89.389459

In [14]:
tree_tt_gen.keys()

[b'rand',
 b'wt_cp_sm',
 b'wt_cp_ps',
 b'wt_cp_mm',
 b'pi_px_1',
 b'pi_py_1',
 b'pi_pz_1',
 b'pi_E_1',
 b'pi2_px_1',
 b'pi2_py_1',
 b'pi2_pz_1',
 b'pi2_E_1',
 b'pi3_px_1',
 b'pi3_py_1',
 b'pi3_pz_1',
 b'pi3_E_1',
 b'pi_px_2',
 b'pi_py_2',
 b'pi_pz_2',
 b'pi_E_2',
 b'pi2_px_2',
 b'pi2_py_2',
 b'pi2_pz_2',
 b'pi2_E_2',
 b'pi3_px_2',
 b'pi3_py_2',
 b'pi3_pz_2',
 b'pi3_E_2',
 b'pi0_px_1',
 b'pi0_py_1',
 b'pi0_pz_1',
 b'pi0_E_1',
 b'pi0_px_2',
 b'pi0_py_2',
 b'pi0_pz_2',
 b'pi0_E_2',
 b'sv_x_1',
 b'sv_y_1',
 b'sv_z_1',
 b'sv_x_2',
 b'sv_y_2',
 b'sv_z_2',
 b'dm_1',
 b'dm_2',
 b'metx',
 b'mety']